In [15]:
import numpy as np
import data1D
from reservoir import Reservoir
from sklearn.model_selection import GridSearchCV

%load_ext autoreload
%autoreload 2
%aimport data1D
%aimport reservoir

%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:

parallel_runs = 1
forget = 100
b = Reservoir(n_res=2000, res_scale=.1, res_encoding=None, res_enc_param=np.pi,
              input_scale=1, input_encoding=None,
              random_projection='simulation', weights_type='gaussian',
              activation_fun='tanh', activation_param=10,
              parallel_runs=parallel_runs,  bias_scale=0.1, leak_rate=0.8,
              pred_horizon=1, rec_pred_steps=200, forget = forget,
              train_method='ridge', train_param=10, verbose=1, gridsearch=True
             )

In [20]:
params = [
  {'res_scale': np.arange(.01, 1, .14),
   'input_scale': np.arange(.01, 1, .14)
   'bias_scale': np.arange(.01, 1, .14),
  }
]

In [21]:
ctanh = GridSearchCV(estimator=b, param_grid=params, return_train_score=True, cv=3, verbose=2)
n_sequence = 1
spatial_points = 30
lyap_exp = 0.0461
ks_data, xx, tt = data1D.kuramoto_sivashinsky_matlab(sequence_length=3000, n_sequence=n_sequence, spatial_points=spatial_points)
input_shape=ks_data.shape
input_data = ks_data.reshape((ks_data.shape[1], ks_data.shape[0], ks_data.shape[2]))
ctanh.fit(input_data)

print(ctanh.best_params_)

Fitting 3 folds for each of 4 candidates, totalling 12 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] input_scale=0.01, res_scale=0.01 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.12566161155700684 s



Reservoir iterations complete. 		Elapsed time: 5.113326549530029 s
Training complete. 			Elapsed time: 0.34906649589538574 s
Training score: 0.9968699527725844
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0009918212890625 s



pred_output = [[-0.136373   -1.16516088 -1.69024578 -1.57533952]
 [-0.24050292 -1.24844972 -1.71275944 -1.54582175]
 [-0.34639483 -1.33019393 -1.73168718 -1.51307936]]
true_output = [[-0.21422892 -1.26556111 -1.75169607 -1.58223217]
 [-0.3245488  -1.3502267  -1.77097593 -1.54897258]
 [-0.43580374 -1.43189857 -1.78572346 -1.51211763]]
Reservoir iterations complete. 		Elapsed time: 8.494287490844727 s
Testing complete. 			Elapsed time: 0.013966083526611328 s
Testing score: 0.03241768487055693
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0019958019256591797 s



pred_output = [[0.2919722  0.83705639 1.5096957  2.05930679]
 [0.28793754 0.82437349 1.4907129  2.05069034]
 [0.28341691 0.80953173 1.46838486 2.03930143]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 10.603646039962769 s
Testing complete. 			Elapsed time: 0.013963699340820312 s
Testing score: 0.21482510869315385
[CV] ................. input_scale=0.01, res_scale=0.01, total=  14.0s


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   24.7s remaining:    0.0s


[CV] input_scale=0.01, res_scale=0.01 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.10969400405883789 s



Reservoir iterations complete. 		Elapsed time: 4.190794229507446 s
Training complete. 			Elapsed time: 0.33510422706604004 s
Training score: 0.9957462945667892
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0009944438934326172 s



pred_output = [[-1.24295397 -1.67798937 -1.46845585 -0.96203172]
 [-1.26416552 -1.69297907 -1.47728713 -0.96815817]
 [-1.28806014 -1.70804426 -1.48440712 -0.97214235]]
true_output = [[-1.26618997 -1.68835774 -1.47042168 -0.97626466]
 [-1.29038563 -1.70335636 -1.47774807 -0.98031317]
 [-1.31724654 -1.71816847 -1.48315537 -0.98206872]]
Reservoir iterations complete. 		Elapsed time: 9.338036060333252 s
Testing complete. 			Elapsed time: 0.013957738876342773 s
Testing score: 0.0027258458215214504
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.003988504409790039 s



pred_output = [[0.29188411 0.84617539 1.52173228 2.06580463]
 [0.28858807 0.83453767 1.5035499  2.05738353]
 [0.28472788 0.8207059  1.48205747 2.04626409]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 11.75456976890564 s
Testing complete. 			Elapsed time: 0.013966798782348633 s
Testing score: 0.18377791115570175
[CV] ................. input_scale=0.01, res_scale=0.01, total=  13.9s
[CV] input_scale=0.01, res_scale=0.01 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.10970497131347656 s



Reservoir iterations complete. 		Elapsed time: 3.693125009536743 s
Training complete. 			Elapsed time: 0.3720059394836426 s
Training score: 0.9970340711235273
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.001996755599975586 s



pred_output = [[0.32616439 0.85602688 1.53195349 2.08452866]
 [0.32274602 0.84563438 1.51547632 2.07834066]
 [0.31896118 0.83331778 1.49579572 2.06941923]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 7.999605655670166 s
Testing complete. 			Elapsed time: 0.011969566345214844 s
Testing score: 0.0024625407601423276
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0019953250885009766 s



pred_output = [[-1.24847758 -1.67817927 -1.46395851 -0.95792383]
 [-1.27013759 -1.69349867 -1.47303568 -0.96405165]
 [-1.29446613 -1.70882041 -1.48034502 -0.96797432]]
true_output = [[-1.26618997 -1.68835774 -1.47042168 -0.97626466]
 [-1.29038563 -1.70335636 -1.47774807 -0.98031317]
 [-1.31724654 -1.71816847 -1.48315537 -0.98206872]]
Reservoir iterations complete. 		Elapsed time: 9.836697101593018 s
Testing complete. 			Elapsed time: 0.012965679168701172 s
Testing score: 0.17942886455919105
[CV] ................. input_scale=0.01, res_scale=0.01, total=  12.1s
[CV] input_scale=0.01, res_scale=0.51 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.1096949577331543 s



Reservoir iterations complete. 		Elapsed time: 3.6771678924560547 s
Training complete. 			Elapsed time: 0.3610343933105469 s
Training score: 0.9971823607715029
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.000997781753540039 s



pred_output = [[-0.14112249 -1.17305105 -1.69842721 -1.58062815]
 [-0.24572199 -1.25675904 -1.72114336 -1.5510496 ]
 [-0.35204603 -1.33884122 -1.74017757 -1.51817538]]
true_output = [[-0.21422892 -1.26556111 -1.75169607 -1.58223217]
 [-0.3245488  -1.3502267  -1.77097593 -1.54897258]
 [-0.43580374 -1.43189857 -1.78572346 -1.51211763]]
Reservoir iterations complete. 		Elapsed time: 8.074410200119019 s
Testing complete. 			Elapsed time: 0.012965679168701172 s
Testing score: 0.03642845402538922
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0009975433349609375 s



pred_output = [[0.29236004 0.83763579 1.51033358 2.05992067]
 [0.28813321 0.82455241 1.49095278 2.05111022]
 [0.28341152 0.80929411 1.46820266 2.03949845]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 9.923465251922607 s
Testing complete. 			Elapsed time: 0.014976263046264648 s
Testing score: 0.2249847240226929
[CV] ................. input_scale=0.01, res_scale=0.51, total=  12.2s
[CV] input_scale=0.01, res_scale=0.51 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.10970592498779297 s



Reservoir iterations complete. 		Elapsed time: 3.654229164123535 s
Training complete. 			Elapsed time: 0.36003708839416504 s
Training score: 0.9960693179779889
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0009970664978027344 s



pred_output = [[-1.24154431 -1.67545415 -1.46575139 -0.96019992]
 [-1.26280806 -1.69039976 -1.47447175 -0.96618774]
 [-1.28675432 -1.70541038 -1.48146483 -0.97001809]]
true_output = [[-1.26618997 -1.68835774 -1.47042168 -0.97626466]
 [-1.29038563 -1.70335636 -1.47774807 -0.98031317]
 [-1.31724654 -1.71816847 -1.48315537 -0.98206872]]
Reservoir iterations complete. 		Elapsed time: 8.133252143859863 s
Testing complete. 			Elapsed time: 0.012965202331542969 s
Testing score: 0.0039048424091898226
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0019953250885009766 s



pred_output = [[0.29238228 0.84518682 1.51975947 2.06415544]
 [0.28889521 0.83319171 1.50121776 2.05550532]
 [0.28483325 0.81898114 1.47933808 2.04412774]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 9.779849290847778 s
Testing complete. 			Elapsed time: 0.01296687126159668 s
Testing score: 0.19365468173781725
[CV] ................. input_scale=0.01, res_scale=0.51, total=  12.2s
[CV] input_scale=0.01, res_scale=0.51 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.11068940162658691 s



Reservoir iterations complete. 		Elapsed time: 3.647247552871704 s
Training complete. 			Elapsed time: 0.348069429397583 s
Training score: 0.9972971852159205
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0009965896606445312 s



pred_output = [[0.32510979 0.8553468  1.53227173 2.08577854]
 [0.32144099 0.84442989 1.51518357 2.07915354]
 [0.31738782 0.83155917 1.49485597 2.06976617]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 8.080394506454468 s
Testing complete. 			Elapsed time: 0.012964963912963867 s
Testing score: 0.0027160051425717713
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.001994609832763672 s



pred_output = [[-1.24683306 -1.67696302 -1.46360618 -0.95835832]
 [-1.26863592 -1.69226712 -1.4724988  -0.96424181]
 [-1.29311661 -1.70757098 -1.47961049 -0.96790501]]
true_output = [[-1.26618997 -1.68835774 -1.47042168 -0.97626466]
 [-1.29038563 -1.70335636 -1.47774807 -0.98031317]
 [-1.31724654 -1.71816847 -1.48315537 -0.98206872]]
Reservoir iterations complete. 		Elapsed time: 9.765886783599854 s
Testing complete. 			Elapsed time: 0.013963460922241211 s
Testing score: 0.1857297864229966
[CV] ................. input_scale=0.01, res_scale=0.51, total=  12.1s
[CV] input_scale=0.51, res_scale=0.01 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.10970497131347656 s



Reservoir iterations complete. 		Elapsed time: 3.653231382369995 s
Training complete. 			Elapsed time: 0.3700110912322998 s
Training score: 0.9994110254080532
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.000997304916381836 s



pred_output = [[-0.24903335 -1.307561   -1.78752469 -1.58700922]
 [-0.35200043 -1.38958473 -1.81097417 -1.56035628]
 [-0.45623318 -1.46898102 -1.83040214 -1.53106228]]
true_output = [[-0.21422892 -1.26556111 -1.75169607 -1.58223217]
 [-0.3245488  -1.3502267  -1.77097593 -1.54897258]
 [-0.43580374 -1.43189857 -1.78572346 -1.51211763]]
Reservoir iterations complete. 		Elapsed time: 8.05745530128479 s
Testing complete. 			Elapsed time: 0.010983705520629883 s
Testing score: 0.04183242072223721
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.001994609832763672 s



pred_output = [[0.29899521 0.84784684 1.51290037 2.05755856]
 [0.29425366 0.83283477 1.49092166 2.0447844 ]
 [0.28866314 0.81523937 1.4652043  2.02868126]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 9.821740627288818 s
Testing complete. 			Elapsed time: 0.012961387634277344 s
Testing score: 0.2639102878834779
[CV] ................. input_scale=0.51, res_scale=0.01, total=  12.1s
[CV] input_scale=0.51, res_scale=0.01 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.1107029914855957 s



Reservoir iterations complete. 		Elapsed time: 3.6961169242858887 s
Training complete. 			Elapsed time: 0.3370985984802246 s
Training score: 0.9986648534242187
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0009984970092773438 s



pred_output = [[-1.04181849 -1.4286636  -1.30611656 -0.91876854]
 [-1.06981631 -1.44724841 -1.31512747 -0.9231933 ]
 [-1.1008218  -1.46593558 -1.3223388  -0.92531176]]
true_output = [[-1.26618997 -1.68835774 -1.47042168 -0.97626466]
 [-1.29038563 -1.70335636 -1.47774807 -0.98031317]
 [-1.31724654 -1.71816847 -1.48315537 -0.98206872]]
Reservoir iterations complete. 		Elapsed time: 8.116297721862793 s
Testing complete. 			Elapsed time: 0.011971235275268555 s
Testing score: 0.07912960795918035
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.001995086669921875 s



pred_output = [[0.30616834 0.8502735  1.50874907 2.05581518]
 [0.29983384 0.83410475 1.48634697 2.04287828]
 [0.29243731 0.81531093 1.46037048 2.02668045]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 9.858638763427734 s
Testing complete. 			Elapsed time: 0.011968851089477539 s
Testing score: 0.38154971048628017
[CV] ................. input_scale=0.51, res_scale=0.01, total=  12.2s
[CV] input_scale=0.51, res_scale=0.01 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.10970568656921387 s



Reservoir iterations complete. 		Elapsed time: 3.721050262451172 s
Training complete. 			Elapsed time: 0.3640263080596924 s
Training score: 0.9993284454033757
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0009918212890625 s



pred_output = [[0.37850033 0.91127491 1.5382333  2.06426374]
 [0.37646892 0.89766253 1.51592337 2.04928889]
 [0.3735846  0.88134355 1.48982147 2.03113168]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 8.071425914764404 s
Testing complete. 			Elapsed time: 0.012958526611328125 s
Testing score: 0.02236772910323869
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.001995563507080078 s



pred_output = [[-1.27757874 -1.70181485 -1.47868906 -0.97944939]
 [-1.30194359 -1.71681172 -1.48595355 -0.98368719]
 [-1.32885652 -1.73142544 -1.4911731  -0.98562263]]
true_output = [[-1.26618997 -1.68835774 -1.47042168 -0.97626466]
 [-1.29038563 -1.70335636 -1.47774807 -0.98031317]
 [-1.31724654 -1.71816847 -1.48315537 -0.98206872]]
Reservoir iterations complete. 		Elapsed time: 9.852653980255127 s
Testing complete. 			Elapsed time: 0.011969566345214844 s
Testing score: 0.14969107381513921
[CV] ................. input_scale=0.51, res_scale=0.01, total=  12.2s
[CV] input_scale=0.51, res_scale=0.51 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.10970497131347656 s



Reservoir iterations complete. 		Elapsed time: 3.6761698722839355 s
Training complete. 			Elapsed time: 0.35804271697998047 s
Training score: 0.9994487815135084
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0009965896606445312 s



pred_output = [[-0.22504268 -1.27749863 -1.77076399 -1.57988005]
 [-0.32919556 -1.3589056  -1.79163497 -1.54999204]
 [-0.43451515 -1.43738299 -1.80795238 -1.51720515]]
true_output = [[-0.21422892 -1.26556111 -1.75169607 -1.58223217]
 [-0.3245488  -1.3502267  -1.77097593 -1.54897258]
 [-0.43580374 -1.43189857 -1.78572346 -1.51211763]]
Reservoir iterations complete. 		Elapsed time: 8.079396724700928 s
Testing complete. 			Elapsed time: 0.013969182968139648 s
Testing score: 0.041354628623156066
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0029888153076171875 s



pred_output = [[0.30254492 0.84826866 1.50841169 2.05132947]
 [0.29713224 0.83325984 1.48721515 2.03995858]
 [0.29077994 0.81565218 1.46233372 2.02532005]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 9.86661696434021 s
Testing complete. 			Elapsed time: 0.012965679168701172 s
Testing score: 0.4549525955635593
[CV] ................. input_scale=0.51, res_scale=0.51, total=  12.2s
[CV] input_scale=0.51, res_scale=0.51 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.11069607734680176 s



Reservoir iterations complete. 		Elapsed time: 3.6761701107025146 s
Training complete. 			Elapsed time: 0.36801648139953613 s
Training score: 0.9987416091499265
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0009968280792236328 s



pred_output = [[-0.93247126 -1.3231539  -1.24378474 -0.89943451]
 [-0.96040413 -1.34214984 -1.25345952 -0.90423681]
 [-0.99163342 -1.36146409 -1.26142747 -0.90673068]]
true_output = [[-1.26618997 -1.68835774 -1.47042168 -0.97626466]
 [-1.29038563 -1.70335636 -1.47774807 -0.98031317]
 [-1.31724654 -1.71816847 -1.48315537 -0.98206872]]
Reservoir iterations complete. 		Elapsed time: 8.197147846221924 s
Testing complete. 			Elapsed time: 0.011968851089477539 s
Testing score: 0.11256122494922358
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.001995086669921875 s



pred_output = [[0.31246725 0.85703905 1.51358016 2.0572182 ]
 [0.30559874 0.84028931 1.49108621 2.04508359]
 [0.29762791 0.8207787  1.46475981 2.0294179 ]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 9.966350555419922 s
Testing complete. 			Elapsed time: 0.011971473693847656 s
Testing score: 0.5407711394968902
[CV] ................. input_scale=0.51, res_scale=0.51, total=  12.3s
[CV] input_scale=0.51, res_scale=0.51 ................................
Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.10970592498779297 s



Reservoir iterations complete. 		Elapsed time: 3.8616740703582764 s
Training complete. 			Elapsed time: 0.3590400218963623 s
Training score: 0.9993712269596112
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0009970664978027344 s



pred_output = [[0.36067173 0.85953333 1.50154152 2.06234153]
 [0.35753475 0.8461845  1.48071843 2.0502193 ]
 [0.35350892 0.8303696  1.45626836 2.03484664]]
true_output = [[0.29832833 0.8422505  1.50255029 2.04731924]
 [0.2927631  0.82699817 1.48134577 2.03635891]
 [0.28651278 0.80946637 1.4567273  2.02221932]]
Reservoir iterations complete. 		Elapsed time: 8.09834599494934 s
Testing complete. 			Elapsed time: 0.012966394424438477 s
Testing score: 0.024987863252767775
Reservoir Computing algorithm - Testing phase:

Initialization complete. 		Elapsed time: 0.0019834041595458984 s



pred_output = [[-1.27218511 -1.69659877 -1.47594051 -0.97820786]
 [-1.29688932 -1.71173023 -1.48297746 -0.98209779]
 [-1.3241292  -1.72652844 -1.48800801 -0.98370437]]
true_output = [[-1.26618997 -1.68835774 -1.47042168 -0.97626466]
 [-1.29038563 -1.70335636 -1.47774807 -0.98031317]
 [-1.31724654 -1.71816847 -1.48315537 -0.98206872]]
Reservoir iterations complete. 		Elapsed time: 9.812761545181274 s
Testing complete. 			Elapsed time: 0.013964176177978516 s
Testing score: 0.19716926930583076
[CV] ................. input_scale=0.51, res_scale=0.51, total=  12.4s


[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:  4.5min finished


Reservoir Computing algorithm - Training phase:

Initialization complete. 		Elapsed time: 0.10970568656921387 s



Reservoir iterations complete. 		Elapsed time: 5.500293016433716 s
Training complete. 			Elapsed time: 0.27028536796569824 s
Training score: 0.9996356240271881
{'input_scale': 0.51, 'res_scale': 0.51}
